name: build
on:
  push:
    branches:
      - cicd
jobs:
  test-build:
    if: job.test.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: flutter pub get
        id: flutter-get
        run: flutter pub get
      - name: flutter test
        id: flutter-test
        run: flutter test
      - name: Build APK
        id: flutter-build
        if: steps.flutter-test.outcome == 'success'
        run: flutter build apk --release --build-number=$GITHUB_RUN_NUMBER